---
driver:
   name: vagrant

provisioner:
  name: chef_zero
  #chef_omnibus_url: https://www.chef.io/chef/install.sh

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[dbag::default]
    attributes:
